version: 2
archives:
- files:
  - deploy/systemd
  - LICENSE
  - README.md

builds:
- id: piv-agent
  binary: piv-agent
  main: ./cmd/piv-agent
  ldflags:
  - >
    -s -w
    -X "main.commit={{.Commit}}"
    -X "main.date={{.Date}}"
    -X "main.projectName={{.ProjectName}}"
    -X "main.version=v{{.Version}}"
  env:
  - CGO_ENABLED=1
  goos:
  - linux
  goarch:
  - amd64

changelog:
  use: github-native

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_linux_checksums.txt"

release:
  extra_files:
  - glob: "{{ .Env.GITHUB_SBOM_PATH }}"
    name_template: "{{ .ProjectName }}.v{{ .Version }}.sbom.linux.spdx.json"
