name: Tag to Release
on:
  push:
    tags:
    - v*
jobs:
  release:
    strategy:
      # avoid concurrent goreleaser runs
      max-parallel: 1
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Go
      uses: actions/setup-go@v3
      with:
        go-version: "^1.18"
    - name: Install Dependencies (ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get update && sudo apt-get -u install libpcsclite-dev
    - name: Set up environment
      run: echo "GOVERSION=$(go version)" >> $GITHUB_ENV
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        version: latest
        args: release --rm-dist --config .goreleaser.${{ matrix.os }}.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
