name: Test
on: pull_request
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get -u install libpcsclite-dev
    - name: Run Tests
      run: go test -v ./...
